baseURL = "https://codehakase.com/"
languageCode = "en-us"
title = "codehakase"
theme = "clean"

[params]
  mainSections = ["post", "posts", "blog"]
  description = "Francis Sunday's personal website"
  twitter = "@codehakase"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
    style = "colorful"
    tabWidth = 4
    lineNos = false
    noClasses = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
 
 [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
    

summaryLength = 20
showAllPostsArchive = true


[taxonomies]
   tag = "tags"

[permalinks]
  posts = "/:year-:month-:day/:title"
