baseURL = "https://codehakase.com/"
languageCode = "en-us"
title = "Francis Sunday"
theme = "clean"

[params]
  mainSections = ["post", "posts", "blog"]
  description = "Francis Sunday's personal website"
  twitter = "@codehakase"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
    style = "bw"
    tabWidth = 4
    lineNos = false
    noClasses = true

summaryLength = 20
showAllPostsArchive = true

[[menu.main]]
name = "Home"
url = "/blog"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Archive"
url = "/archive/"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/codehakase"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/codehakase"

[taxonomies]
   tag = "tags"

[permalinks]
  posts = "/:year-:month-:day/:title"
