baseURL = "https://codehakase.com/"
languageCode = "en-us"
title = "Francis Sunday"
theme = "clean"
enableRobotsTXT = true

[params]
  mainSections = ["blog", "shorts"]
  description = "Francis Sunday's personal website"
  twitter = "@codehakase"
  maths = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
    style = "xcode"
    tabWidth = 4
    lineNos = false
    noClasses = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
 
 [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]
    

summaryLength = 10
showAllPostsArchive = true


[taxonomies]
   tag = "tags"

[permalinks]
  blog = "/blog/:title"
  shorts = "/shorts/:title"
